### ISSUE TITLE
Возможно проблема с обработкой параметра Durations

### ISSUE THREAD

**Issue by dr-wut** [YPermitin/YY.TechJournalReaderAssistant#11]
Добрый день
Заметил что данные о длительности запроса в поле Durations больше на порядок чем в логе (такое ощущение что к полю пока оно текстовое добавляется 0)
В связи с этим едут все показания  дальнейшие.

**Comment by YPermitin** [comment]
Нужно больше информации.

Пришлите пример файла ТЖ, напишите версию платформы 1С и тд.

**Comment by dr-wut** [comment]
Версия 1С - 8.3.15.1830
Логи выслать не смогу - инфобез против, но проблема в том, что поля Duration между 0 и 10 - просто нет. В логах - 3, в клике - 30, ну и так далее

**Comment by dr-wut** [comment]
https://github.com/YPermitin/YY.TechJournalReaderAssistant/blob/769c877aa34f1dbfcc5e7f93a4e6c48001565394/YY.TechJournalReaderAssistant/LogParserTechJournal.cs#L133
Вот тут идет умножение на 10 или на 100. Я так понимаю что должно быть или на 1 или на 100. Или второго умножения делать вообще не надо по идее (которое на 1(10)).

**Comment by YPermitin** [comment]
@dr-wut Проблема исправлена, библиотеки чтения и экспорта обновлены.

Можете обновить их в своем приложении через Nuget.
